### ISSUE TITLE
pft-make: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by haary** [dacav/App-PFT#7]
Just tried PFT and failed with following error message when running  `pft make`

`pft: Died at /usr/local/share/perl/5.28.1/PFT/Map.pm line 126.`
`pft: cannot run command make: Inappropriate ioctl for device`

What I did:
~~~
$ mkdir site
$ cd site
$ pft init
$ pft edit -B a test
~~~
Content:
~~~
---
Author: haary
Date: 2020-07-17
Options:
  hide: 0
  template: ~
Slug: a-test
Tags: ~
Title: 'a test'
---

a test
~~~

~~~
$ pft make
pft: Died at /usr/local/share/perl/5.28.1/PFT/Map.pm line 126.

pft: cannot run command make: Inappropriate ioctl for device`
~~~

Running on Debian 10 x86_64

**Comment by dacav** [comment]
Hello.

First off, it looks like the error message is misleading.  [There we go](https://github.com/dacav/App-PFT/issues/8), I opened myself an issue :) .

That said, it looks like an assertion is not met. The only thing I could think of is that you have another entry with the same Slug `a-test`... is that the case?

If so you are not allowed to have two entries with the same slug.  Yet PFT should definitely fail gracefully, in this case, so I'll have to fix it.

**Comment by dacav** [comment]
Fixed.
https://github.com/dacav/PFT/commit/f73690d05d0b439354cb5b4b5aeabbebd8f879ba

**Comment by haary** [comment]
No, I haven't another entry with the same slug. Tested it on another machine with the same OS now, same error.

**Comment by dacav** [comment]
Weird.  Then I can't reproduce it with the sequence of commands you defined.
What version of App::PFT and PFT are you running?

If you are running the latest release of PFT (the library) you should be able to just apply the patch above (or you can manually change the code to do the same).  Do you get any interesting behaviour if you do so?

In short, this is a slug collision, and with the patch the system should gracefully fail to compile one entry, instead of crashing. It will also print on stderr the identifier that collided, and this could give us some clue.

**Comment by dacav** [comment]
@haary  - any news on this one? :)

**Comment by dacav** [comment]
Could not verify, reporter is not responsive.
